### ISSUE TITLE
想问下为什么没有后台代码还能从后台获取到json数据

### ISSUE THREAD

**Issue by Goinsist** [lhz960904/movie-trailer#3]
本地运行后为什么没有后台代码还能通过接口获取数据
methods: {
    getMovie () {
      this.$axios.get('/api/movie/get_hot').then(res => {
        if (res.code === 1001) {
          const { comming, playing } = res.result
          this.commingMovies = comming.movies
          this.commingCount = comming.count
          this.playingMovies = playing.movies
          this.playingCount = playing.count
        }
      })
    },

**Comment by 1377637225** [comment]
现在没了，哈哈

**Comment by 1377637225** [comment]
> 本地运行后为什么没有后台代码还能通过接口获取数据
> methods: {
> getMovie () {
> this.$axios.get('/api/movie/get_hot').then(res => {
> if (res.code === 1001) {
> const { comming, playing } = res.result
> this.commingMovies = comming.movies
> this.commingCount = comming.count
> this.playingMovies = playing.movies
> this.playingCount = playing.count
> }
> })
> },

项目根目录下的*vue.config.js*文件中，有个 target， 你 ping 一下就知道了

**Comment by lhz960904** [comment]
> 本地运行后为什么没有后台代码还能通过接口获取数据
> methods: {
> getMovie () {
> this.$axios.get('/api/movie/get_hot').then(res => {
> if (res.code === 1001) {
> const { comming, playing } = res.result
> this.commingMovies = comming.movies
> this.commingCount = comming.count
> this.playingMovies = playing.movies
> this.playingCount = playing.count
> }
> })
> },

通过wepack的proxy做的请求代理，在vue.config.js里配置。 代理到后端代码的服务。后端代码地址 -> [https://github.com/lhz960904/movie-api](https://github.com/lhz960904/movie-api)
